feat: update user (hashed password)
WildCodeSchool/2109-wns-remote3-back pull request #84
Opened 2022-05-03 17:03 UTC by loic-bodolec

hash the new user's password

2022-05-23 12:10 UTC, nicholas570 requested changes

2022-05-23 12:10 UTC, nicholas570 commented on src/domain/services/user/UserService.ts
> +    const result = await this.repository.update(user.id, modifyUser);
This will create a new User and hash its password at every request.
You should consider create a specific endpoint where you would get the user and only update its password

2022-05-23 12:51 UTC, loic-bodolec commented on src/domain/services/user/UserService.ts
> +    const result = await this.repository.update(user.id, modifyUser);
Thanks for this feedback!

2022-05-23 15:09 UTC, loic-bodolec commented on src/domain/services/user/UserService.ts
> +    const result = await this.repository.update(user.id, modifyUser);
it's done.

2022-05-24 09:19 UTC, nicholas570 approved these changes

2022-05-24 09:20 UTC, merged